from __future__ import annotations

from typing import Dict, Any


def starter_web_app(prompt: str) -> Dict[str, Any]:
    return {
        "summary": f"Starter web app for: {prompt}",
        "files": {
            "app.py": "from flask import Flask\n\napp = Flask(__name__)\n\n@app.route('/')\ndef index():\n    return 'Hello from the AI coding assistant starter app'\n\nif __name__ == '__main__':\n    app.run(debug=True)\n",
            "requirements.txt": "Flask==3.0.3\n",
        },
    }


def starter_cli_tool(prompt: str) -> Dict[str, Any]:
    return {
        "summary": f"Starter CLI tool for: {prompt}",
        "files": {
            "main.py": "def main():\n    print('This CLI was generated for: {}')\n\n\nif __name__ == '__main__':\n    main()\n".format(prompt),
            "requirements.txt": "",
        },
    }


def starter_api(prompt: str) -> Dict[str, Any]:
    return {
        "summary": f"Starter API for: {prompt}",
        "files": {
            "main.py": "from fastapi import FastAPI\n\napp = FastAPI()\n\n@app.get('/')\ndef root():\n    return {'message': 'API generated by the AI coding assistant'}\n",
            "requirements.txt": "fastapi==0.111.0\nuvicorn==0.30.3\n",
        },
    }
