from __future__ import annotations

from typing import Any, Dict


def starter_web_app(prompt: str) -> Dict[str, Any]:
    return {
        "summary": f"Starter web app for: {prompt}",
        "files": {
            "app.py": (
                "from fastapi import FastAPI\n\n"
                "app = FastAPI()\n\n"
                "@app.get('/health')\n"
                "def health():\n"
                "    return {'status': 'ok'}\n\n"
                "@app.get('/')\n"
                "def root():\n"
                "    return {'message': 'Hello from the AI coding assistant'}\n"
            ),
            "requirements.txt": "fastapi==0.111.0\nuvicorn==0.30.3\n",
        },
    }


def starter_cli_tool(prompt: str) -> Dict[str, Any]:
    return {
        "summary": f"Starter CLI tool for: {prompt}",
        "files": {
            "main.py": (
                "def main():\n"
                f"    print('This CLI was generated for: {prompt}')\n\n\n"
                "if __name__ == '__main__':\n"
                "    main()\n"
            ),
            "requirements.txt": "",
        },
    }


def starter_api(prompt: str) -> Dict[str, Any]:
    return {
        "summary": f"Starter API for: {prompt}",
        "files": {
            "main.py": (
                "from fastapi import FastAPI\n\n"
                "app = FastAPI(title='Generated API')\n\n"
                "@app.get('/')\n"
                "def root():\n"
                "    return {'message': 'API generated by the AI coding assistant'}\n"
            ),
            "requirements.txt": "fastapi==0.111.0\nuvicorn==0.30.3\n",
        },
    }
